version: '3'
services:
  mysql-GPTChatHelperDB:
    image: mysql:latest
    container_name: mysql-GPTChatHelperDB
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: gptdb
    ports:
      - 3306:3306
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  mysql-data: