spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/gptdb}
    driver-class-name: com.mysql.cj.jdbc.Driver

  openai:
    apikey: ${OPENAI_API_KEY:null}